version: '3.8'

services:
  ruvsarpur-web:
    build: 
      context: .
    image: sillkongen/ruvsarpur-web:latest
    container_name: ruvsarpur-web
    ports:
      - "5000:5000"    # Flask frontend
      - "8001:8001"    # FastAPI backend
    volumes:
      # EPG/Schedule data - use local directory with correct permissions
      - type: bind
        source: ./data/epg
        target: /home/appuser/.ruvsarpur
        consistency: delegated
      # Downloads directory - persist in host's downloads directory
      - type: bind
        source: ./downloads
        target: /app/downloads
        consistency: delegated
      # Local data directory as fallback
      - type: bind
        source: ./data
        target: /app/data
        consistency: delegated
    environment:
      - PYTHONPATH=/app:/app/ruvsarpur
      - RUVSARPUR_PATH=/app/ruvsarpur
      - FLASK_ENV=production
      # EPG data locations in order of preference
      - SCHEDULE_FILE=/home/appuser/.ruvsarpur/tvschedule.json
      - SCHEDULE_FILE_FALLBACK=/app/data/.ruvsarpur/tvschedule.json
      # Host user ID and group ID for file ownership
      - HOST_UID=${HOST_UID:-1000}
      - HOST_GID=${HOST_GID:-1000}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 3
    # Add a command to ensure directory exists before starting
    command: >
      bash -c "
        mkdir -p /home/appuser/.ruvsarpur &&
        /app/entrypoint.sh
      " 