version: '3.8'

services:
  ruvsarpur-web:
    build: 
      context: .
      args:
        - USER_ID=${USER_ID:-1000}
        - GROUP_ID=${GROUP_ID:-1000}
    ports:
      - "5000:5000"    # Flask frontend
      - "8001:8001"    # FastAPI backend
    volumes:
      # EPG/Schedule data - persist in host user's home directory, mounted to appuser in container
      - ${HOME}/.ruvsarpur:/home/appuser/.ruvsarpur
      # Downloads directory - persist in host's downloads directory  
      - ./downloads:/app/downloads/
      # Local data directory as fallback
      - ./data:/app/data
      # ruvsarpur is now included in the repository - no external mount needed
    environment:
      - PYTHONPATH=/app:/app/ruvsarpur
      - RUVSARPUR_PATH=/app/ruvsarpur
      - FLASK_ENV=production
      # EPG data locations in order of preference
      - SCHEDULE_FILE=/home/appuser/.ruvsarpur/tvschedule.json
      - SCHEDULE_FILE_FALLBACK=/app/data/.ruvsarpur/tvschedule.json
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 3 