name: CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Check Python syntax
      run: |
        python -m py_compile app.py
        python -m py_compile database.py
        python -m py_compile backend/app/main.py
    
    - name: Test Docker build
      run: |
        docker build -t ruvsarpur-web-test .
    
    - name: Test Docker Compose
      run: |
        # Create minimal test structure
        mkdir -p downloads data
        
        # Test compose file syntax
        docker-compose config
        
        # Test build process
        docker-compose build
    
    - name: Clean up
      if: always()
      run: |
        docker system prune -f 